version: '3'  # The version of the Docker Compose file format
services:  # Define the services/containers we want to create

  postgres:  # The name of the first service/container
    image: postgres:latest  # The Docker image to use (latest version of PostgreSQL)
    restart: "always"
    container_name: postsgres
    environment:
      POSTGRES_USER: sram-admin  # Set the PostgreSQL username
      POSTGRES_PASSWORD: sramsram-admin  # Set the PostgreSQL password
      POSTGRES_DB: db  # Set the name of the PostgreSQL database
    ports:
      - "5432:5432"  # Map host port 5432 to container port 5432 (i.e., host:container)
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Create a Docker volume for PostgreSQL data

  redis:  # The name of the second service/container
    image: redis:latest  # The Docker image to use (latest version of Redis)
    restart: "always"
    ports:
      - "6379-6381:6379"  # Map host port rangin from 6379 to 6381 to container port 6379
    deploy:
      replicas: 3
    environment:
      DEMO: demo

volumes:
  postgres_data:  # Define the Docker volume for PostgreSQL data



